import js from '@eslint/js';
import jsdoc from 'eslint-plugin-jsdoc';
import globals from 'globals';

export default [
	js.configs.recommended,
	jsdoc.configs['flat/recommended'],
	{
		languageOptions: {
			ecmaVersion: 2025,
			sourceType: 'module',
			globals: {
				...globals.browser,
				...globals.es2021,
				structuredClone: 'readonly',
				ResizeObserver: 'readonly',
				AbortController: 'readonly',
				AbortSignal: 'readonly',
				requestIdleCallback: 'readonly',
				cancelIdleCallback: 'readonly',
			},
		},
		plugins: {
			jsdoc,
		},
		rules: {
			'no-console': ['warn', { allow: ['warn', 'error', 'assert'] }],
			'no-unused-vars': ['error', {
				argsIgnorePattern: '^_',
				destructuredArrayIgnorePattern: '^_',
				varsIgnorePattern: '^_',
				caughtErrorsIgnorePattern: '^_'
			}],
			'prefer-const': 'error',
			'no-var': 'error',
			'arrow-spacing': 'error',
			'object-shorthand': 'error',
			'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
			'prefer-destructuring': ['error', { object: true, array: false }],
			'prefer-template': 'error',
			'template-curly-spacing': 'error',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'no-duplicate-imports': 'error',
			'no-useless-rename': 'error',
			'symbol-description': 'error',
			'no-iterator': 'error',
			'no-restricted-globals': ['error', 'event', 'fdescribe'],
			'consistent-return': 'error',
			'default-case-last': 'error',
			'default-param-last': 'error',
			'eqeqeq': ['error', 'always', { null: 'ignore' }],
			'grouped-accessor-pairs': 'error',
			'guard-for-in': 'error',
			'no-alert': 'warn',
			'no-caller': 'error',
			'no-constructor-return': 'error',
			'no-eval': 'error',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-floating-decimal': 'error',
			'no-implicit-coercion': ['error', { allow: ['!!'] }],
			'no-implied-eval': 'error',
			'no-invalid-this': 'error',
			'no-labels': 'error',
			'no-lone-blocks': 'error',
			'no-loop-func': 'error',
			'no-multi-spaces': 'error',
			'no-multi-str': 'error',
			'no-new': 'error',
			'no-new-func': 'error',
			'no-new-wrappers': 'error',
			'no-octal-escape': 'error',
			'no-param-reassign': ['error', { props: false }],
			'no-proto': 'error',
			'no-return-assign': 'error',
			'no-script-url': 'error',
			'no-self-compare': 'error',
			'no-sequences': 'error',
			'no-throw-literal': 'error',
			'no-unmodified-loop-condition': 'error',
			'no-unused-expressions': ['error', {
				allowShortCircuit: true,
				allowTernary: true,
				allowTaggedTemplates: true
			}],
			'no-useless-call': 'error',
			'no-useless-concat': 'error',
			'no-useless-return': 'error',
			'no-void': 'error',
			'no-with': 'error',
			'prefer-promise-reject-errors': 'error',
			'prefer-regex-literals': 'error',
			'radix': 'error',
			'require-await': 'error',
			'yoda': 'error',
			'jsdoc/check-alignment': 'error',
			'jsdoc/check-param-names': 'error',
			'jsdoc/check-tag-names': 'error',
			'jsdoc/check-types': 'error',
			'jsdoc/require-description': 'warn',
			'jsdoc/require-jsdoc': [
				'warn',
				{
					require: {
						FunctionDeclaration: true,
						MethodDefinition: true,
						ClassDeclaration: true,
						ArrowFunctionExpression: false,
						FunctionExpression: false,
					},
					contexts: [
						'ExportNamedDeclaration > FunctionDeclaration',
						'ExportDefaultDeclaration > FunctionDeclaration'
					]
				},
			],
			'jsdoc/require-param': 'error',
			'jsdoc/require-param-description': 'warn',
			'jsdoc/require-param-type': 'error',
			'jsdoc/require-returns': 'error',
			'jsdoc/require-returns-description': 'warn',
			'jsdoc/require-returns-type': 'error',
			'jsdoc/require-hyphen-before-param-description': 'error',
			'jsdoc/no-multi-asterisks': 'error',
			'jsdoc/tag-lines': ['error', 'never'],
			'jsdoc/check-indentation': 'warn',
			'jsdoc/no-undefined-types': 'error',
		},
		files: ['**/*.js', '**/*.mjs'],
		ignores: [
			'node_modules/**',
			'dist/**',
			'coverage/**',
			'**/*.min.js',
			'build/**',
			'**/vendor/**',
			'reports/**',
			'test-results/**',
			'playwright-report/**',
			'.vitest/**',
		],
	},
	{
		files: ['**/*.test.js', '**/*.spec.js'],
		rules: {
			'no-console': 'off',
			'jsdoc/require-jsdoc': 'off',
			'no-unused-expressions': 'off',
		},
	},
	{
		files: ['**/*.config.js', '**/*.config.mjs', 'eslint.config.js'],
		languageOptions: {
			globals: {
				...globals.node,
			},
		},
		rules: {
			'jsdoc/require-jsdoc': 'off',
			'no-console': 'off',
		},
	},
];
