name: CHANGELOG Generator

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-changelog:
    name: Generate CHANGELOG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper changelog generation
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate CHANGELOG
        run: |
          # Determine base branch
          BASE_BRANCH="${{ github.base_ref }}"

          # Generate changelog from base branch to current HEAD
          node scripts/generate-changelog.js --from "origin/${BASE_BRANCH}" --to HEAD

          echo "CHANGELOG generation complete"

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet CHANGELOG.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes to CHANGELOG.md"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "CHANGELOG.md has been updated"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG.md [skip ci]"
          git push origin HEAD:${{ github.head_ref }}

      - name: Comment on PR
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const changelog = fs.readFileSync('CHANGELOG.md', 'utf8');
            const unreleasedMatch = changelog.match(/## \[Unreleased\] - [\d-]+\s*\n([\s\S]*?)(?=\n## |\Z)/);

            let changelogPreview = '';
            if (unreleasedMatch) {
              changelogPreview = unreleasedMatch[0].trim();
            }

            const comment = `## 📝 CHANGELOG Updated

            The CHANGELOG has been automatically updated based on your commits:

            <details>
            <summary>View Changes</summary>

            \`\`\`markdown
            ${changelogPreview || 'No preview available'}
            \`\`\`

            </details>

            The changes have been committed to this PR.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: No changes message
        if: steps.check_changes.outputs.changed == 'false'
        run: |
          echo "ℹ️  No new changelog entries generated. This might mean:"
          echo "   - No commits found between base and head"
          echo "   - Commits don't follow conventional commit format"
          echo "   - CHANGELOG already up to date"
